// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => webButLinux;

  static FirebaseOptions webButLinux = FirebaseOptions(
      apiKey: "AIzaSyDOmDMV6MfYRHgiMlH1W_gNHhw10bin8V8",
      authDomain: "project-corntrack.firebaseapp.com",
      projectId: "project-corntrack",
      storageBucket: "project-corntrack.firebasestorage.app",
      messagingSenderId: "800040482536",
      appId: "1:800040482536:web:f37979d531dd97648ebb5d",
      measurementId: "G-X7VG1PVTD3"
  );
}
