name: Build Flutter .deb Package

on:
  push:
    branches:
      - test2
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.0

      - name: Enable Linux Desktop Support
        run: |
          sudo apt update
          sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev -y
          flutter config --enable-linux-desktop

      - name: Build Flutter for Linux
        run: flutter build linux

      - name: Prepare DEB Package Structure
        run: |
          rm -rf corntrack_raspberry_pi_app

          mkdir -p corntrack_raspberry_pi_app/DEBIAN
          mkdir -p corntrack_raspberry_pi_app/usr/local/bin
          mkdir -p corntrack_raspberry_pi_app/usr/share/applications
          mkdir -p corntrack_raspberry_pi_app/usr/share/icons/hicolor/256x256/apps

          cp build/linux/x64/release/bundle/corntrack_raspberry_pi_app corntrack_raspberry_pi_app/usr/local/bin/corntrack_raspberry_pi_app

          cat <<EOF > corntrack_raspberry_pi_app/DEBIAN/control
          Package: corntrack_raspberry_pi_app
          Version: 1.0.0
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: A Flutter-based desktop application for Raspberry Pi
          EOF

          cat <<EOF > corntrack_raspberry_pi_app/usr/share/applications/corntrack_raspberry_pi_app.desktop
          [Desktop Entry]
          Name=corntrack_raspberry_pi_app
          Comment=Raspberry Pi Flutter Desktop App
          Exec=/usr/local/bin/corntrack_raspberry_pi_app
          Icon=/usr/share/icons/hicolor/256x256/apps/corntrack_raspberry_pi_app.png
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF

          chmod +x corntrack_raspberry_pi_app/usr/local/bin/corntrack_raspberry_pi_app

      - name: Build the .deb Package
        run: dpkg-deb --build corntrack-rpi-app

      - name: Upload DEB Package as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-deb
          path: corntrack_raspberry_pi_app.deb
