name: Build Flutter .deb Package

on:
  push:
    branches:
      - test2
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.0

      - name: Enable Linux Desktop Support
        run: |
          sudo apt update
          sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev binfmt-support -y
          flutter config --enable-linux-desktop

      - name: Set Up Cross-compilation Environment for ARM64 (aarch64)
        run: |
          # Install necessary ARM64 cross-compilation dependencies
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

          # Set up QEMU to emulate ARM64
          sudo apt-get install -y qemu-user-static
          sudo update-binfmts --enable qemu-aarch64

      - name: Build Flutter for ARM64 (aarch64)
        run: |
          # Ensure we are building the app for ARM64
          flutter build linux

      - name: List build output (ARM64 Debug)
        run: ls -l build/linux/arm64/release/bundle

      - name: Prepare DEB Package Structure for ARM64
        run: |
          # Remove previous package structure
          rm -rf corntrackrpi_rpi

          # Create necessary directories for the .deb package
          mkdir -p corntrackrpi_rpi/DEBIAN
          mkdir -p corntrackrpi_rpi/usr/local/bin
          mkdir -p corntrackrpi_rpi/usr/share/applications
          mkdir -p corntrackrpi_rpi/usr/share/icons/hicolor/256x256/apps

          # Copy the binary to the correct location in the DEB package
          cp build/linux/arm64/release/bundle/corntrack_raspberry_pi_app corntrackrpi_rpi/usr/local/bin/corntrackrpi

          # Create control file for DEB package
          cat <<EOF > corntrackrpi_rpi/DEBIAN/control
          Package: corntrackrpi
          Version: 1.0.0
          Section: base
          Priority: optional
          Architecture: arm64
          Maintainer: Your Name <your.email@example.com>
          Description: A Flutter-based desktop application for Raspberry Pi (ARM64)
          EOF

          # Create desktop entry file for the application
          cat <<EOF > corntrackrpi_rpi/usr/share/applications/corntrackrpi.desktop
          [Desktop Entry]
          Name=corntrackrpi
          Comment=Raspberry Pi Flutter Desktop App
          Exec=/usr/local/bin/corntrackrpi
          Icon=/usr/share/icons/hicolor/256x256/apps/corntrackrpi.png
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF

          # Make the binary executable
          chmod +x corntrackrpi_rpi/usr/local/bin/corntrackrpi

      - name: Build the .deb Package for ARM64 (Raspberry Pi)
        run: dpkg-deb --build corntrackrpi_rpi

      - name: Upload DEB Package as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: corntrackrpi_arm64
          path: corntrackrpi_rpi.deb
