name: Build Flutter .deb Package

on:
  push:
    branches:
      - test2
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.0

      - name: Enable Linux Desktop Support
        run: |
          sudo apt update
          sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev -y
          flutter config --enable-linux-desktop

      - name: Build Flutter for Linux
        run: flutter build linux

      - name: Prepare DEB Package Structure
        run: |
          rm -rf corntrackrpi

          mkdir -p corntrackrpi/DEBIAN
          mkdir -p corntrackrpi/usr/local/bin
          mkdir -p corntrackrpi/usr/share/applications
          mkdir -p corntrackrpi/usr/share/icons/hicolor/256x256/apps

          cp build/linux/x64/release/bundle/corntrackrpi corntrackrpi/usr/local/bin/corntrackrpi

          cat <<EOF > corntrackrpi/DEBIAN/control
          Package: corntrackrpi
          Version: 1.0.0
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: A Flutter-based desktop application for Raspberry Pi
          EOF

          cat <<EOF > corntrackrpi/usr/share/applications/corntrackrpi.desktop
          [Desktop Entry]
          Name=corntrackrpi
          Comment=Raspberry Pi Flutter Desktop App
          Exec=/usr/local/bin/corntrackrpi
          Icon=/usr/share/icons/hicolor/256x256/apps/corntrackrpi.png
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF

          chmod +x corntrackrpi/usr/local/bin/corntrackrpi

      - name: Build the .deb Package
        run: dpkg-deb --build corntrackrpi

      - name: Upload DEB Package as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-deb
          path: corntrackrpi.deb
